### ISSUE TITLE
POST FAILED - Response: -1

### ISSUE THREAD

**Issue by hsadeghilam** [tobiasschuerg/ESP8266_Influx_DB#1]
I've been using the library for a couple of weeks with no issue, but since Friday I've been getting this error:

<- Response: -1 ""
#####
POST FAILED

I'm running influxdb on my local computer. Any idea what's causing this?

**Comment by boianmihailov** [comment]
I am getting the same issue. Were you able to fix it ?

**Comment by hsadeghilam** [comment]
I figured it was not a library issue. I was connecting ESP to my PC through a router and my PC IP was changing! So I just had to update the IP and it worked!

**Comment by tobiasschuerg** [comment]
@boianmihailov did you manage to resolve your issue as well?

**Comment by boianmihailov** [comment]
@tobiasschuerg yes, it turned out to be issue with influx server. ESP could not connect to it at all. Looking at the other responses I guess the only thing you could improve on it the error returned when its not able to connect. 

Thanks a lot for the great work btw. Appreciated 👍

**Comment by tobiasschuerg** [comment]
The error/status returned are those from the `httpClient`:

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h#L44-L55

```
/// HTTP client errors
#define HTTPC_ERROR_CONNECTION_REFUSED  (-1)
#define HTTPC_ERROR_SEND_HEADER_FAILED  (-2)
#define HTTPC_ERROR_SEND_PAYLOAD_FAILED (-3)
#define HTTPC_ERROR_NOT_CONNECTED       (-4)
#define HTTPC_ERROR_CONNECTION_LOST     (-5)
#define HTTPC_ERROR_NO_STREAM           (-6)
#define HTTPC_ERROR_NO_HTTP_SERVER      (-7)
#define HTTPC_ERROR_TOO_LESS_RAM        (-8)
#define HTTPC_ERROR_ENCODING            (-9)
#define HTTPC_ERROR_STREAM_WRITE        (-10)
#define HTTPC_ERROR_READ_TIMEOUT        (-11)
```
