### ISSUE TITLE
Support String in addValue(String key, String value)

### ISSUE THREAD

**Issue by mihino** [tobiasschuerg/ESP8266_Influx_DB#11]
I have added new method in InfluxData.h to suport also String as a value.
I needed to add changing access points MAC address, or changing DHCP IP address so it's not a tag but a value.
Please consider to add it also your lib.
thanks

`
  void addValue(String key, String value) {
    _values = (_values == "") ? (" ") : (_values += ",");
    _values += key + "=\"" + value + "\"";
  }
`

**Comment by tobiasschuerg** [comment]
I think this is now added with https://github.com/tobiasschuerg/ESP8266_Influx_DB/pull/16
