### ISSUE TITLE
invalid conversion type influxdb_port

### ISSUE THREAD

**Issue by crazycusti** [tobiasschuerg/ESP8266_Influx_DB#29]
Hello!

if i change the port, the compiler will break. i try to change the data type but no success.

any ideas? :(

here my log:

Arduino: 1.8.10 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 IPv6 Higher Bandwidth, Disabled, None, Only Sketch, 115200"

bme280influxdb:16:45: error: invalid conversion from 'const char*' to 'uint16_t {aka short unsigned int}' [-fpermissive]
 Influxdb influx(INFLUXDB_HOST, INFLUXDB_PORT);
                                             ^
In file included from /home/wynton/Arduino/bme280influxdb/bme280influxdb.ino:6:0:
/home/wynton/Arduino/libraries/ESP8266_Influxdb/InfluxDb.h:24:3: error:   initializing argument 2 of 'Influxdb::Influxdb(String, uint16_t)' [-fpermissive]
   Influxdb(String host, uint16_t port = 8086);
   ^

exit status 1
invalid conversion from 'const char*' to 'uint16_t {aka short unsigned int}' [-fpermissive]

**Comment by tobiasschuerg** [comment]
Sounds like you are passing a `String` instead of an `Integer`.
Try to remove the `"` for port:

```
Influxdb influx("192.168.0.32", 1234);
```
