### ISSUE TITLE
Username and password for DB privilege

### ISSUE THREAD

**Issue by Stifler6996** [tobiasschuerg/ESP8266_Influx_DB#3]
nudge nudge!
[https://github.com/tobiasschuerg/ESP8266_Influx_DB/blob/9f7629093ae85aba290313a3c71237b0f8ffd8e1/InfluxDb.cpp#L32](https://github.com/tobiasschuerg/ESP8266_Influx_DB/blob/9f7629093ae85aba290313a3c71237b0f8ffd8e1/InfluxDb.cpp#L32
)

This variant of your library [https://github.com/teebr/Influx-Arduino ](https://github.com/teebr/Influx-Arduino )  ((You posted a comment about multiple points at this library also!!!)) already has password for database.

Perhaps you can implement this also?

**Comment by tobiasschuerg** [comment]
Yeah, right. That's still a TODO :-)

**Comment by ghoeffner** [comment]
Looking for this as well @tobiasschuerg :) Would be an "awesome" to have ;)

**Comment by jotzt** [comment]
Pull request with authentication support is pending.

**Comment by tobiasschuerg** [comment]
[Version 1.1.0](https://github.com/tobiasschuerg/ESP8266_Influx_DB/releases/tag/1.1.0) is out. @Stifler6996  @ghoeffner
