### ISSUE TITLE
V2 Support

### ISSUE THREAD

**Issue by davidgs** [tobiasschuerg/ESP8266_Influx_DB#9]
Not really an issue, but I forked your library and ported it over to InfluxDBv2.0 so it works with the new release. See https://github.com/davidgs/ESP8266_Influx_DB_V2

**Comment by tobiasschuerg** [comment]
I woudl be happy to merge your [Pull Request.](https://github.com/tobiasschuerg/ESP8266_Influx_DB/compare).

Already checked if I could quickly create a PR to merge back your changes but it seems that you copied all the code into a new repo, instead of creating a fork.

**Comment by davidgs** [comment]
I looked at doing this as a PR, etc. but given the changes, it did not appear to be possible to make the v1.x library co-exist with the v2 stuff since the Authentication, etc. has changed so much. 

I can, if you'd rather, look again at doing it that way and do it as a fork of your code instead. Let me know if you'd like me to do that.

**Comment by davidgs** [comment]
Went back and did this as a fork/PR, now submitted.

**Comment by tobiasschuerg** [comment]
Thanks, added it as separate brancht.
